### ISSUE TITLE
USER STORY: Editing Profile Details

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/XPLORER#34]
### **Epic** #3 

**As a registered user,**  
I want to edit my profile information  
so that I can keep my details up-to-date.

#### **Acceptance Criteria:**
- GIVEN I am on my profile page,
- WHEN I click on the 'Edit' button,
- THEN I should be able to modify my details.

- GIVEN I have made changes to my details,
- WHEN I click on the 'Save' button,
- THEN my updated information should be saved and reflected on my profile page.

#### **Tasks:**
- [x] Implement an 'Edit' button on the profile page.
- [x] Create an editing interface or form.
- [x] Connect the form to the backend to update user details in the database.
