### ISSUE TITLE
USER STORY: Changing Profile Picture

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/XPLORER#35]
### **Epic** #3

**As a registered user,**  
I want to change my profile picture  
so that I can personalize my profile.

#### **Acceptance Criteria:**
- GIVEN I am on my profile page,
- WHEN I click on my current profile picture or a 'Change Picture' button,
- THEN I should be able to upload a new picture.

- GIVEN I have selected a new picture,
- WHEN I confirm the change,
- THEN my new profile picture should be displayed on my profile.

#### **Tasks:**
- [ ] Implement a 'Change Picture' button or clickable profile picture.
- [x] Create an interface to upload images.
- [x] Resize and store the new profile picture in the database or cloud storage.
- [x] Update the profile picture on the user's profile.

**Comment by kpetrauskas92** [comment]
Change profile picture was implemented with US: #34
