### ISSUE TITLE
USER STORY: Adding Images to Post

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/XPLORER#38]
### **Epic** #4 

**As a user,**  
I want to add images to my post  
so that my content can be more engaging and descriptive.

#### **Acceptance Criteria:**
- GIVEN I am on the post creation page,
- WHEN I upload an image and click 'Submit',
- THEN my post with the image should be published on the platform.

#### **Tasks:**
- [x] Implement an image upload button.
- [x] Store uploaded images in a dedicated server or cloud storage.
- [x] Display the uploaded image as a part of the post.
