### ISSUE TITLE
USER STORY: Tagging in Posts

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/XPLORER#39]
### **Epic** #4 

**As a user,**  
I want to add tags to my post  
so that it can be more discoverable to users interested in that topic.

#### **Acceptance Criteria:**
- GIVEN I am creating a post,
- WHEN I add tags and publish the post,
- THEN the post should be associated with those tags and discoverable by them.

#### **Tasks:**
- [ ] Design an input field for tagging.
- [ ] Implement auto-suggestions for commonly used tags.
- [ ] Store associated tags with the post in the database.
