### ISSUE TITLE
USER STORY: Post Edit

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/XPLORER#41]
### **Epic** #4 

**As a user,**  
I want to edit my previously created post  
so that I can correct mistakes or update its content.

#### **Acceptance Criteria:**
- GIVEN I am viewing a post I've created,
- WHEN I click the 'Edit' button, make changes, and save,
- THEN the post should be updated with the changes I made.

#### **Tasks:**
- [x] Implement an 'Edit' button for posts created by the user.
- [x] Create an interface similar to post creation for editing the content.
- [x] Update the post in the database with the new changes.
