### ISSUE TITLE
USER STORY: Unfollow a User

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/XPLORER#50]
### **Epic** #7 

**As a user,**  
I want to unfollow a user  
so that I no longer see their content in my news feed.

#### **Acceptance Criteria:**

- GIVEN I am viewing a user's profile that I currently follow or accessing my following list,
- WHEN I click the 'Unfollow' button,
- THEN that user should be removed from my following list and their content should stop appearing in my news feed.

#### **Tasks:**
- [x] Design and implement the 'Unfollow' button on user profiles and in following lists.
- [x] Update backend databases to remove the following relationship.
- [x] Adjust the news feed algorithm to exclude posts from unfollowed users.
