### ISSUE TITLE
USER STORY: View Followers and Following Lists

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/XPLORER#51]
### **Epic** #7 

**As a user,**  
I want to view lists of users who follow me and users I am following  
so that I can manage and understand my network on the platform.

#### **Acceptance Criteria:**

- GIVEN I am on my profile page,
- WHEN I click on 'Followers' or 'Following' links/sections,
- THEN I should see lists of users who follow me and users I am following, respectively.

#### **Tasks:**
- [ ] Design sections or pages for 'Followers' and 'Following' on user profiles.
- [ ] Fetch and display lists from the backend databases.
- [ ] Implement features to easily navigate to each user's profile from the lists.
